Update haskell.yml

diff --git a/.github/workflows/haskell.yml b/.github/workflows/haskell.yml
--- a/.github/workflows/haskell.yml
+++ b/.github/workflows/haskell.yml
@@ -7,34 +7,56 @@ on:
     branches: [ main, action_test ]
 
 jobs:
-  build:
-
-    runs-on: ubuntu-latest
+  stack:
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest, macOS-latest]
+        plan:
+          - ghc: '8.10.3'
+            resolver: 'lts-17.2'
+          - ghc: '8.8.3'
+            resolver: 'lts-16.11'
+          - ghc: '8.6.5'
+            resolver: 'lts-14.27'
+          - ghc: '8.4.4'
+            resolver: 'lts-12.26'
+        ## include:
+        ##   - os: macOS-latest
+        ##     flags: '--flag greskell:-hint-test'
+            
+    runs-on: ${{ matrix.os }}
+    continue-on-error: ${{ matrix.plan.allow-fail == true }}
+    env:
+      STACK: stack --no-terminal --system-ghc --resolver ${{ matrix.plan.resolver }}
+      FLAGS: ${{ matrix.flags }}
 
     steps:
     - uses: actions/checkout@v2
-    - uses: actions/setup-haskell@v1
+      
+    - uses: haskell/actions/setup@v1
+      id: cabal-setup-haskell
       with:
-        ghc-version: '8.10.3'
-        cabal-version: '3.2'
+        ghc-version: ${{ matrix.plan.ghc }}
+        enable-stack: true
 
-    - name: Cache
-      uses: actions/cache@v1
-      env:
-        cache-name: cache-cabal
+    - uses: actions/cache@v2
+      ## Looks like caching in macOS causes weird failures in the steps later.
+      if: runner.os != 'macOS'
       with:
-        path: ~/.cabal
-        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
-        restore-keys: |
-          ${{ runner.os }}-build-${{ env.cache-name }}-
-          ${{ runner.os }}-build-
-          ${{ runner.os }}-
+        path: ~/.stack
+        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ matrix.plan.resolver }}
+    
+    - name: Configure
+      run: |
+        set -ex
+        rm -f stack.yaml.lock
+        $STACK clean
 
     - name: Install dependencies
-      run: |
-        cabal update
-        cabal build --only-dependencies --enable-tests --enable-benchmarks
+      run: $STACK test --bench --only-dependencies $FLAGS
     - name: Build
-      run: cabal build --enable-tests --enable-benchmarks all
-    - name: Run tests
-      run: cabal test all
+      run: $STACK build --bench --haddock --no-haddock-deps $FLAGS
+    - name: Test
+      run: $STACK -j 1 test --bench --no-run-benchmarks --haddock --no-haddock-deps $FLAGS
+
